/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom1_8 (
    input [4:0] selector,
    output reg [37:0] out
  );
  
  
  
  localparam INPUTS = 874'h000540008284b400038c51a0000a115bd000580b22acd11aac3a5ad2586ce92e49e001500116000040003700000000dc00000007700010000d400000007500000001cc00000003300010001060001fffc17fffffff040007fffc10001ffff0230ab88a0072cb6200000057ffec0;
  
  always @* begin
    out = INPUTS[(selector)*38+37-:38];
  end
endmodule
